# hyprlock — lockscreen (tema Tokyo Night)
# Docs: https://wiki.hypr.land/Hypr-Ecosystem/hyprlock/

general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = false
}

background {
    monitor =
    color = rgba(16161eff)
    blur_passes = 0
}

# Relógio
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(c0caf5ff)
    font_size = 110
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 80
    halign = center
    valign = center
}

# Data
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    color = rgba(565f89ff)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
}

# Avatar / usuário
label {
    monitor =
    text =   $USER
    color = rgba(7aa2f7ff)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = bottom
}

# Campo de senha
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(292e42ff)
    inner_color = rgba(1a1b26ff)
    font_color = rgba(c0caf5ff)
    check_color = rgba(9ece6aff)
    fail_color = rgba(f7768eff)
    fail_text = <i>Senha incorreta</i>
    placeholder_text = <i>Senha...</i>
    rounding = 12
    position = 0, 0
    halign = center
    valign = bottom
}
