[Colors]
accent=#e6b450
background=#0b0e14
background_fullscreen=#0b0e14
folderview=#0f131a
folderview_topbar=#1e222a
icons=#bfbdb6
overlay=#0f131a
overlay_text=#bfbdb6
scrollbar=#565b66
text=#bfbdb6
widget=#0f131a
widget_border=#1e222a
